name: portugoose
description: A sample command-line application.
version: 1.0.0
publish_to: none

environment:
  sdk: ^3.1.3

dependencies:
  collection: ^1.18.0
  functions_framework: ^0.4.0
  shelf: ^1.0.0
  chatterbox: ^1.0.3
#  chatterbox:
#    path: ../../chatterbox
  ai_assistant:
    path: ./ai_assistant

dev_dependencies:
  build_runner: ^2.0.0
  functions_framework_builder: ^0.4.0
  lints: ^2.0.0
  test: ^1.21.0
