name: portugoose
description: A sample command-line application.
version: 1.0.0
publish_to: none

environment:
  sdk: ^3.1.3

dependencies:
  collection: ^1.18.0

  # Networking
  functions_framework: ^0.4.0
  shelf: ^1.0.0

  # App packages
  ai_assistant:
    path: ./ai_assistant
  database:
    path: ./database

  # Telegram
#  chatterbox: ^1.0.4
  chatterbox:
    path: ../../chatterbox

dev_dependencies:
  build_runner: ^2.0.0
  functions_framework_builder: ^0.4.0
  lints: ^2.0.0
  test: ^1.21.0

dependency_overrides:
  http: ^1.1.0